// Generated by Selenium IDE
using OpenQA.Selenium;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace PicoPlacaPredictor.Tests.UI
{
    [TestClass]
    public partial class MoreInfoModalTest : BrowserNavegationTest
    {
        PACHome pageAction = new PACHome();
        [TestMethod]
        public void MoreInfoModal()
        {
            pageAction.NavegateToLocalWebApp(driver);
            driver.FindElement(By.Id("moreInfoButton")).Click();
            var elements = driver.FindElements(By.CssSelector("img"));
            Assert.IsTrue(elements.Count > 0);
        }
    }
}